// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221221185304_InserindoUsuarios")]
    partial class InserindoUsuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f29ebb27-1591-4b9e-ab2c-354094870175"),
                            CreateAt = new DateTime(2022, 12, 21, 15, 53, 4, 71, DateTimeKind.Local).AddTicks(8297),
                            Email = "adm@mail.com",
                            Name = "Administrador",
                            UpdateAt = new DateTime(2022, 12, 21, 15, 53, 4, 72, DateTimeKind.Local).AddTicks(9131)
                        },
                        new
                        {
                            Id = new Guid("75a68fc9-98b6-4537-bc9d-9cc5d71b71b0"),
                            CreateAt = new DateTime(2022, 12, 21, 15, 53, 4, 72, DateTimeKind.Local).AddTicks(9453),
                            Email = "vino@mail.com",
                            Name = "Vinicius",
                            UpdateAt = new DateTime(2022, 12, 21, 15, 53, 4, 72, DateTimeKind.Local).AddTicks(9461)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
